### ISSUE TITLE
declared version of jackson-module-kotlin is not released

### ISSUE THREAD

**Issue by jensim** [FasterXML/jackson-bom#51] opened 2022-03-08 13:21 UTC
https://github.com/FasterXML/jackson-bom/blob/jackson-bom-2.13.2/pom.xml#L52
This says the `jackson-module-kotlin` version should be same as the other versions.

But that version does not seem to be released 🤷🏻

🤦🏻? Or am I doing it wrong?

It (2.13.2) is not listed here: https://github.com/FasterXML/jackson-module-kotlin/tags
Nor here: https://search.maven.org/artifact/com.fasterxml.jackson.module/jackson-module-kotlin

I would have done a PR, but there is no 2.* working branch that I see, and I don't wanna do it wrong ☺️

I've got a work-around in place - so im not really affected by this.

Big ❤️ for Jackson

**Comment by cowtowncoder** [comment] 2022-03-08 19:15
No, you are not doing anything wrong. The problem is due to:

https://github.com/FasterXML/jackson-module-kotlin/issues/550

which we hope to resolve ASAP.

**Comment by cowtowncoder** [comment] 2022-03-30 04:34
Module was eventually released, closing.

**Closed by cowtowncoder** 2022-03-30 04:34 UTC
